name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: Create venv
      run: uv venv
    - name: Run tests
      run: make test
    # build and store whl as artifact
    - name: Build and store whl
      if: matrix.os == 'ubuntu-latest'
      run: |
        make build
        mkdir -p ${{ github.workspace }}/artifacts
        cp dist/*.whl ${{ github.workspace }}/artifacts/
    - name: Upload whl artifact for this build
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: mcp-scan-latest.whl
        path: ${{ github.workspace }}/artifacts/*.whl
